version: "3"

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - ../postgres-data:/var/lib/postgresql/data
      - ./sql/0001_bootstrap_db.sql:/docker-entrypoint-initdb.d/create_tables.sql

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

